sudo: required
service:
 - docker
before_install:# this is image creation for travis from docker file 
  - docker build -t kkaruna9/travis:v3.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push kkaruna9/travis:v3.0 # i am pushing my image to hub.docker.com reposiorty
notifications:
 email:
   recipients:
     - krishnamoorthyk2@gmail.com
   on_success: always
   on_failure: always
