# this file will be used by travis to build image and push the image to hub.docker.com.However there is 2 things also will be automated as part of thi excercise.1. whenevr there is change in the code (dockerfile the trigger will be initated.2. if there is any issue in the build automatically the final image wont be pushed.
sudo: required
service:
 - docker
before_install:#  image creation form docker file 
  - docker build -t kkaruna9/travis:v3.0 .
script:
 - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
 - docker images # to verify image is build or not
 - docker push kkaruna9/travis:v3.0 #  pushing image to hub.docker.com reposiorty
notifications:
 email:
   recipients:
     - krishnamoorthyk2@gmail.com
   on_success: always
   on_failure: always
